function rand(i) {
	return Math.floor(Math.random() * i);
}

function randarr(arr, i) {
	return arr[rand(arr.length)];
}

var MAX = rand(800);

var phrasetab = [
	"Mcdonalds",
	"SR-71 Aeromorph",
	"Visualization",
	"Murdoch",
	"Hillary",
	"Hillary Clinton",
	"Clinton Foundation",
	"Obamacare",
	"Conspiracy",
	"UFO",
	"field",
	"poison",
	"brainwash",
	"care",
	"test",
	"no",
	"but",
	"a",
	"not",
	"used to",
	"however",
	"creation",
	"was there",
	"alien",
	"being",
	"Milky way",
	"synt.us",
	"no help",
	"however found out a new way to",
	"hello",
	"meditation",
	"techniques",
	"technique",
	"<a href='http://synt.us/research/'>which you can find here, I think",
	"it's great",
	"erection",
	"IBM",
	"Dell",
	"sticky",
	"are",
	"radical",
	"leftism",
	"rightism",
	"left-wing",
	"right-wing",
	"Death Grips",
	"XXXTentacion",
	"Britney Spears",
	"Hiele",
	"Kalx",
	"Big L",
	"Ridge Racer",
	"<a href='http://lhohq.info/libor-report/libor-threat.html'>Osamu Sato</a>",
	"Skrillex",
	"I love to kill introverted <a href='http://synt.us/research/cursor-inhabitant/'>women</a>",
	"<br />",
	"<font style='color: #ff0000;'>matches</font>",
	"<b>it's not the issue today anymore</b>",
	"format",
	"LHOHQ",
	"GCHQ",
	"JTRIG",
	"Pentagon",
	"DCSPIM",
	"SIM card",
	"organ",
	"Cellular",
	"machinery",
	"machine",
	"pedophile",
	"pedophiles",
	"selwyn",
	"asylum",
	"mentality",
	"strength",
	"endurance",
	"NetFlix",
	"Facebook",
	"satan sacrifice",
	"facebook",
	"MySpace",
	"myspace",
	"god",
	"God",
	"cure",
	"primordial",
	"love",
	"Ukraine",
	"America",
	"spoken",
	"words",
	"tuned",
	"tune",
	"radio",
	"MSM Brainwash",
	"Joseph",
	"National Socialism"
];

var body = document.getElementsByTagName("body")[0];
document.title = randarr(phrasetab);

body.innerHTML += "<p>";
for (var i = 0; i < MAX; i++)
	body.innerHTML += randarr(phrasetab) + " ";
body.innerHTML += "</p>";
